export const PLATFORMS = {
  SAAS: 'SAAS',
  IFOOD: 'IFOOD',
  KEETA: 'KEETA',
  FOOD99: 'FOOD99',
};

export const ENTRY_TYPES = {
  SALE: 'SALE',
  REFUND: 'REFUND',
  CANCELLATION: 'CANCELLATION',
  FEE: 'FEE',
  ADJUSTMENT: 'ADJUSTMENT',
};

export const CONNECTION_STATUS = {
  NOT_CONNECTED: 'NOT_CONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  SYNCING: 'SYNCING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ERROR: 'ERROR',
  DISCONNECTED: 'DISCONNECTED',
};

export default { PLATFORMS, ENTRY_TYPES, CONNECTION_STATUS };
