require('dotenv').config();

module.exports = {
  port: process.env.PORT || 3000,
  jwtSecret: process.env.JWT_SECRET,
  evolutionUrl: process.env.EVOLUTION_URL,
  evolutionApiKey: process.env.EVOLUTION_API_KEY,
  evolutionInstance: process.env.EVOLUTION_INSTANCE,
  mapboxToken: process.env.MAPBOX_TOKEN,
  graphhopperKey: process.env.GRAPHHOPPER_KEY,
  geoapifyKey: process.env.GEOAPIFY_KEY,
  databaseUrl: process.env.DATABASE_URL,
  directUrl: process.env.DIRECT_URL,
  supabaseUrl: process.env.SUPABASE_URL,
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY,
  asaasAccessToken: process.env.ASAAS_ACCESS_TOKEN,
  asaasWebhookToken: process.env.ASAAS_WEBHOOK_TOKEN,
  asaasEnv: process.env.ASAAS_ENV || 'production',
  asaasPixExpiryMin: Number(process.env.ASAAS_PIX_EXPIRY_MIN) || 5,
  asaasPixFeePercent: Number(process.env.ASAAS_PIX_FEE_PERCENT) || 2,
  pixSyncCron: process.env.PIX_SYNC_CRON || '*/2 * * * *',
  pedidoRetencaoDias: Number(process.env.PEDIDO_RETENCAO_DIAS) || 30,
  pixEnabled: process.env.PIX_ENABLED === 'true',
  asaasSubcontaKey: process.env.ASAAS_SUBCONTA_KEY,
  ifoodClientId: process.env.IFOOD_CLIENT_ID,
  ifoodClientSecret: process.env.IFOOD_CLIENT_SECRET,
  ifoodAuthorizeUrl: process.env.IFOOD_AUTHORIZE_URL,
  ifoodTokenUrl: process.env.IFOOD_TOKEN_URL,
  ifoodRevokeUrl: process.env.IFOOD_REVOKE_URL,
  ifoodScope: process.env.IFOOD_SCOPE,
  keetaClientId: process.env.KEETA_CLIENT_ID,
  keetaClientSecret: process.env.KEETA_CLIENT_SECRET,
  keetaAuthorizeUrl: process.env.KEETA_AUTHORIZE_URL,
  keetaTokenUrl: process.env.KEETA_TOKEN_URL,
  keetaRevokeUrl: process.env.KEETA_REVOKE_URL,
  keetaScope: process.env.KEETA_SCOPE,
  ninefoodClientId: process.env.NINEFOOD_CLIENT_ID,
  ninefoodClientSecret: process.env.NINEFOOD_CLIENT_SECRET,
  ninefoodAuthorizeUrl: process.env.NINEFOOD_AUTHORIZE_URL,
  ninefoodTokenUrl: process.env.NINEFOOD_TOKEN_URL,
  ninefoodRevokeUrl: process.env.NINEFOOD_REVOKE_URL,
  ninefoodScope: process.env.NINEFOOD_SCOPE,
  marketplaceEnv: process.env.MARKETPLACE_ENV || 'sandbox',
  oauthRedirectBase: process.env.OAUTH_REDIRECT_BASE,
};
